### PR TITLE
Update api_export.go

### PR DESCRIPTION
**Pull request by fabioboterolyons**
import os package, show an error when trying to run a project with the package goflagr

### CODE REVIEW

**Comment by zhouzhuojie** [comment]
hmm, this looks like a bug of `swaggerapi/swagger-codegen-cli`, do you have an idea what's the gap? I'm also going to add CI test for this project.

**Comment by fabioboterolyons** [comment]
[ In the line 104 -> var v *os.File ] use the os package but it isn't imported so it fails when you try to run

**Comment by fabioboterolyons** [comment]
I fork the proyect

**Comment by zhouzhuojie** [comment]
thanks for reporting, I've fixed it with https://github.com/checkr/goflagr/pull/5 via goimports, also added CI for future changes.

**Pull request closed without merging**
